### ISSUE TITLE
Some improvement suggestions

### ISSUE THREAD

**Issue by jm-o** [nsayer/Crazy-Clock#1]
Hello Nick,

I made some changes in Makefile to do it work on my Ubuntu laptop:
- added AVR_PATH variable,
- changed avr binary related variables and DUDE_OPTS.

I added a function to set the corrective offset to the clock in eeprom with avrdude:
- Makefile: 
  - new function 'offset' (see offset.hex and offset.md)
  - offset added in init function
- offset.hex:
  - new file in Intel HEX file format to set the corrective offset
  - default value : none (0)
- offset.md: offset.hex documentation
- README.md: add the offset function at the end of the text
  NB : Seems correct but not fully tested, because it's a bit long to solder/unsolder to test/flash... ;-)

Feel free to use, or not, these elements.

Jean Michel

PS : Remove '.new.txt' to restore the original name 

[Makefile.new.txt](https://github.com/nsayer/Crazy-Clock/files/75245/Makefile.new.txt)
[offset.hex.new.txt](https://github.com/nsayer/Crazy-Clock/files/75246/offset.hex.new.txt)
[offset.md.new.txt](https://github.com/nsayer/Crazy-Clock/files/75247/offset.md.new.txt)
[README.md.new.txt](https://github.com/nsayer/Crazy-Clock/files/75248/README.md.new.txt)

**Comment by jm-o** [comment]
New to github, I decided to fork the repository and to make the above changes over there.

I also added a new clock.

**Comment by nsayer** [comment]
Have you considered putting the rhythm pattern information in program flash instead of EEPROM? I'm not sure I understand what the advantage to using EEPROM instead of a PROGMEM structure.

**Comment by jm-o** [comment]
As I have discovered eeprom can be fed through avrdude to set the corrective offset value, I feel interesting to use it to store more than 6 bytes.

That's the only reason why I use eeprom instead of flash memory.

**Comment by jm-o** [comment]
Flash memory version available ;)
